version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: backend_node_pr3
    hostname: backend
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    restart: always
    depends_on:
      - db
    networks:
      - backend
    volumes:
      - .:/var/www

  db:
    image: postgres:15.3-alpine
    container_name: database
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    env_file:
      - ./.env
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:

volumes:
  postgres_data:
  pgadmin-data: